import asyncio
import json
import sys
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path(__file__).resolve().parent))

from httpx import AsyncClient, ASGITransport
from app.main import app
from app.db.session import init_db

USER_BACKUP = {
  "version": "2.5",
  "app": "car-maintenance-app",
  "exported_at": "2026-08-29T17:04:45",
  "active_vehicle_id": "car_1",
  "vehicle": {
    "id": "car_1",
    "name": "Changan CS55 Plus",
    "brand": "Changan",
    "model": "CS55 Plus",
    "plate": "А381РН252",
    "engine": "1.5T 7DCT",
    "year": 2023,
    "vin": "",
    "current_km": 26636,
    "current_engine_hours": 809,
    "oil_spec": "SAE 0W-20 SP / C5 (4.2 - 4.5 л)",
    "trackers": [
      {
        "id": "engine_oil",
        "name": "Моторное масло (0W-20)",
        "category": "Двигатель",
        "match": "масло",
        "interval_km": 7500,
        "interval_hours": 250,
        "warn_km": 1500,
        "warn_hours": 30,
        "spec": "SAE 0W-20 SP / C5 (4.2 - 4.5 л)",
        "article": "1658134508",
        "brand": "Лукойл Genesis ARMORTECH JP 0W-20",
        "icon": "droplet",
        "enabled": True
      },
      {
        "id": "oil_filter",
        "name": "Масляный фильтр",
        "category": "Фильтры",
        "match": "фильтр масляный",
        "interval_km": 7500,
        "interval_hours": 250,
        "warn_km": 1500,
        "warn_hours": 30,
        "spec": "Changan 1012010MK01 / VIC C-933",
        "article": "16510-61A31",
        "brand": "VIC C-933",
        "icon": "disc",
        "enabled": True
      },
      {
        "id": "air_filter",
        "name": "Воздушный фильтр",
        "category": "Фильтры",
        "match": "фильтр воздушный",
        "interval_km": 15000,
        "interval_hours": 500,
        "warn_km": 1500,
        "warn_hours": 30,
        "spec": "AF162 / Changan 1109190-MK01",
        "article": "1415671763",
        "brand": "AF162",
        "icon": "wrench",
        "enabled": True
      },
      {
        "id": "cabin_filter",
        "name": "Салонный фильтр (угольный)",
        "category": "Фильтры",
        "match": "фильтр салонный",
        "interval_km": 15000,
        "interval_hours": 500,
        "warn_km": 1500,
        "warn_hours": 30,
        "spec": "CN1305K / Changan 8104020-MK01",
        "article": "2220140563",
        "brand": "CN1305K",
        "icon": "wrench",
        "enabled": True
      },
      {
        "id": "drain_washer",
        "name": "Кольцо сливной пробки",
        "category": "Двигатель",
        "match": "кольцо",
        "interval_km": 15000,
        "interval_hours": 500,
        "warn_km": 1500,
        "warn_hours": 30,
        "spec": "21513-23001 (14 мм)",
        "article": "2151323001",
        "brand": "",
        "icon": "wrench",
        "enabled": True
      },
      {
        "id": "spark_plugs",
        "name": "Свечи зажигания (Иридий)",
        "category": "Зажигание",
        "match": "свечи",
        "interval_km": 30000,
        "interval_hours": 0,
        "warn_km": 3000,
        "warn_hours": 0,
        "spec": "Changan HU10A80P / 3707010-NE01",
        "article": "3707010-NE01",
        "brand": "HU10A80P",
        "icon": "zap",
        "enabled": True
      },
      {
        "id": "antifreeze",
        "name": "Антифриз (Охлаждающая жидкость)",
        "category": "Охлаждение",
        "match": "антифриз",
        "interval_km": 50000,
        "interval_hours": 0,
        "warn_km": 5000,
        "warn_hours": 0,
        "spec": "G12+ Dragon FELIX Pink",
        "article": "58888973218",
        "brand": "FELIX DRAGON G12+",
        "icon": "thermometer",
        "enabled": True
      },
      {
        "id": "brake_fluid",
        "name": "Тормозная жидкость",
        "category": "Тормоза",
        "match": "тормозная жидкость",
        "interval_km": 40000,
        "interval_hours": 0,
        "warn_km": 4000,
        "warn_hours": 0,
        "spec": "DOT-4 Class 6",
        "article": "",
        "brand": "",
        "icon": "shield-alert",
        "enabled": False
      },
      {
        "id": "dct_fluid",
        "name": "Масло в коробке РКПП / DCT",
        "category": "Трансмиссия",
        "match": "коробк",
        "interval_km": 50000,
        "interval_hours": 0,
        "warn_km": 5000,
        "warn_hours": 0,
        "spec": "DCTF 7DCT300",
        "article": "",
        "brand": "",
        "icon": "cog",
        "enabled": False
      }
    ]
  },
  "maintenance_records": [
    {
      "id": 19,
      "vehicle_id": "car_1",
      "to_tag": "ТО-2",
      "date": "2026-02-28",
      "engine_hours": 601,
      "mileage": 18378,
      "category": "Двигатель",
      "item_name": "Масло моторное",
      "brand": "ZIC ZERO 20 0W-20",
      "article": "376802873",
      "quantity": 4.0,
      "unit": "л",
      "price_type": "total",
      "price_per_unit": 1051.0,
      "total_price": 4204.0,
      "interval_km": 9000,
      "interval_hours": 250,
      "next_km": 27378,
      "next_hours": 851,
      "note": "Плановая замена",
      "store": "Ozon",
      "url": "https://www.ozon.ru/product/zic-zero-20-0w-20-maslo-motornoe-sinteticheskoe-4-l-376802873/?sh=pkS1vzYyng"
    },
    {
      "id": 20,
      "vehicle_id": "car_1",
      "to_tag": "ТО-2",
      "date": "2026-02-28",
      "engine_hours": 601,
      "mileage": 18378,
      "category": "Фильтры",
      "item_name": "Фильтр масляный ORIGINAL",
      "brand": "Changan",
      "article": "1012010MK01",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 540.0,
      "total_price": 540.0,
      "interval_km": 9000,
      "interval_hours": 250,
      "next_km": 27378,
      "next_hours": 851,
      "note": "Плановая замена",
      "store": "Дилер",
      "url": ""
    },
    {
      "id": 21,
      "vehicle_id": "car_1",
      "to_tag": "ТО-2",
      "date": "2026-02-28",
      "engine_hours": 601,
      "mileage": 18378,
      "category": "Фильтры",
      "item_name": "Фильтр воздушный",
      "brand": "AF162",
      "article": "1415671763",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 803.0,
      "total_price": 803.0,
      "interval_km": 15000,
      "interval_hours": 250,
      "next_km": 33378,
      "next_hours": 851,
      "note": "Плановая замена",
      "store": "Ozon",
      "url": "https://www.ozon.ru/product/filtr-vozdushnyy-changan-cs55-plyus-cs55plus-55-plyus-cs55-chan-gan-cs75-cs75-plyus-cs75plus-75-1415671763/"
    },
    {
      "id": 22,
      "vehicle_id": "car_1",
      "to_tag": "ТО-2",
      "date": "2026-02-28",
      "engine_hours": 601,
      "mileage": 18378,
      "category": "Двигатель",
      "item_name": "Кольцо сливной пробки поддона",
      "brand": "HYUNDAI-KIA",
      "article": "2151323001",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 84.0,
      "total_price": 84.0,
      "interval_km": 15000,
      "interval_hours": 500,
      "next_km": 33378,
      "next_hours": 1101,
      "note": "Плановая замена",
      "store": "Ozon",
      "url": "https://www.ozon.ru/product/uplotnitelnoe-koltso-slivnoy-probki-maslyanogo-poddona-dvigatelya-hyundai-kia-3-sht-2151323001-3280672187/"
    },
    {
      "id": 23,
      "vehicle_id": "car_1",
      "to_tag": "ТО-2",
      "date": "2026-02-28",
      "engine_hours": 601,
      "mileage": 18378,
      "category": "Фильтры",
      "item_name": "Фильтр салонный угольный CS55 Plus",
      "brand": "CN1305K",
      "article": "2220140563",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 798.0,
      "total_price": 798.0,
      "interval_km": 15000,
      "interval_hours": 500,
      "next_km": 33378,
      "next_hours": 1101,
      "note": "Плановая замена",
      "store": "Ozon",
      "url": "https://www.ozon.ru/product/filtr-salonnyy-ugolnyy-changan-cs55-cs55-plus-cs75-plus-cs85-uni-v-i-uni-t-uni-s-uni-z-2220140563/?at=XQtkN8RpyFEOEgkwSLXnVwgiZkGz7Ms9LyJvQuNq7G6A"
    },
    {
      "id": 24,
      "vehicle_id": "car_1",
      "to_tag": "Вне ТО",
      "date": "2025-09-28",
      "engine_hours": 0,
      "mileage": 3000,
      "category": "Детейлинг",
      "item_name": "Пленка на пороги",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 800.0,
      "total_price": 800.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 3000,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "",
      "url": ""
    },
    {
      "id": 25,
      "vehicle_id": "car_1",
      "to_tag": "Вне ТО",
      "date": "2024-09-04",
      "engine_hours": 0,
      "mileage": 1000,
      "category": "Прочее",
      "item_name": "Уплотнитель капота",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 392.0,
      "total_price": 392.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 1000,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": "https://www.ozon.ru/product/uplotnitel-avtomobilnyy-kapota-dveri-avtomobilya-1227524449/?at=1hCk1M7qedrkyElccdsFwNiyNAJm0g0H&sh=Lpetaalhrw"
    },
    {
      "id": 26,
      "vehicle_id": "car_1",
      "to_tag": "Вне ТО",
      "date": "2024-08-14",
      "engine_hours": 0,
      "mileage": 1000,
      "category": "Автотовары",
      "item_name": "Коврики в салон 3D для CHANGAN CS55 PLUS",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "комплект",
      "price_type": "total",
      "price_per_unit": 1493.0,
      "total_price": 1493.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 1000,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": "https://www.ozon.ru/product/kovriki-v-salon-3d-dlya-changan-cs55-plus-2021-n-v-i-rest-uni-s-2024-n-v-vnedorozhnik-5-dv-1348942551/?is_apparel_size_selected=true&sh=Lpetaalhrw"
    },
    {
      "id": 27,
      "vehicle_id": "car_1",
      "to_tag": "Вне ТО",
      "date": "2024-08-14",
      "engine_hours": 0,
      "mileage": 1000,
      "category": "Автотовары",
      "item_name": "Брызговики Changan CS 55 Plus",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "комплект",
      "price_type": "total",
      "price_per_unit": 1439.0,
      "total_price": 1439.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 1000,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": "https://www.ozon.ru/product/bryzgoviki-changan-cs-55-plus-changan-tss-55-plyus-2022-2025-g-v-komplekt-4-sht-perednie-i-zadnie-1163245085/?is_apparel_size_selected=true&sh=LpetaVvjVg"
    },
    {
      "id": 28,
      "vehicle_id": "car_1",
      "to_tag": "Вне ТО",
      "date": "2024-08-14",
      "engine_hours": 0,
      "mileage": 0,
      "category": "Автотовары",
      "item_name": "Коврик в багажник Changan CS55 Plus / UNI-S",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 1339.0,
      "total_price": 1339.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 0,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": ""
    },
    {
      "id": 29,
      "vehicle_id": "car_1",
      "to_tag": "АКБ",
      "date": "2024-09-14",
      "engine_hours": 0,
      "mileage": 0,
      "category": "Аккумулятор",
      "item_name": "Светодиодная подсветка капота автомобиля, силиконовая, ДХО, самоклеящаяся, белая, 1,5 метра",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 553.0,
      "total_price": 553.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 0,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": "https://www.ozon.ru/product/svetodiodnaya-podsvetka-kapota-avtomobilya-silikonovaya-dho-samokleyashchayasya-belaya-1-5-metra-1192389304/?is_apparel_size_selected=true&sh=LpetaTkLfQ"
    },
    {
      "id": 30,
      "vehicle_id": "car_1",
      "to_tag": "АКБ",
      "date": "2024-09-14",
      "engine_hours": 0,
      "mileage": 0,
      "category": "Аккумулятор",
      "item_name": "Разъем автомобильный 2 контакта герметичный",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 153.0,
      "total_price": 153.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 0,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": ""
    },
    {
      "id": 31,
      "vehicle_id": "car_1",
      "to_tag": "Тюнинг",
      "date": "2024-09-04",
      "engine_hours": 0,
      "mileage": 0,
      "category": "Тюнинг и доработки",
      "item_name": "Защитная сетка радиатора в бампер (сетка на решетку радиатора) 1000х400 мм, черная; алюминий",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 584.0,
      "total_price": 584.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 0,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": ""
    },
    {
      "id": 32,
      "vehicle_id": "car_1",
      "to_tag": "Вне ТО",
      "date": "2025-01-12",
      "engine_hours": 0,
      "mileage": 0,
      "category": "Автотовары",
      "item_name": "полочка в подлокотник для Changan CS55Plus. Органайзер в подлокотник Чанган CS55 Плюс",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 318.0,
      "total_price": 318.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 0,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": ""
    },
    {
      "id": 33,
      "vehicle_id": "car_1",
      "to_tag": "Вне ТО",
      "date": "2025-03-20",
      "engine_hours": 0,
      "mileage": 0,
      "category": "Автотовары",
      "item_name": "Накидки на сиденья автомобиля, чехлы на спортивные сиденья",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 2758.0,
      "total_price": 2758.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 0,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": "https://www.ozon.ru/product/nakidki-na-sidenya-avtomobilya-chehly-na-sportivnye-sidenya-744039966/?is_apparel_size_selected=true&sh=LpetaSlexA"
    },
    {
      "id": 34,
      "vehicle_id": "car_1",
      "to_tag": "Вне ТО",
      "date": "2025-06-04",
      "engine_hours": 0,
      "mileage": 0,
      "category": "Автотовары",
      "item_name": "IRQE Шторка солнцезащитная 145 см х 80 см, затемнение: 96%",
      "brand": "",
      "article": "283",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 283.0,
      "total_price": 283.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 0,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": ""
    },
    {
      "id": 39,
      "vehicle_id": "car_1",
      "to_tag": "Тюнинг",
      "date": "2026-05-12",
      "engine_hours": 0,
      "mileage": 0,
      "category": "Тюнинг и доработки",
      "item_name": "Газовые упоры капота для Changan CS55",
      "brand": "",
      "article": "",
      "quantity": 1.0,
      "unit": "комплект",
      "price_type": "total",
      "price_per_unit": 1256.0,
      "total_price": 1256.0,
      "interval_km": 0,
      "interval_hours": 0,
      "next_km": 0,
      "next_hours": 0,
      "note": "Покупка / Доработка",
      "store": "Озон",
      "url": ""
    },
    {
      "id": 40,
      "vehicle_id": "car_1",
      "to_tag": "ТО-3",
      "date": "2026-07-22",
      "engine_hours": 772,
      "mileage": 25340,
      "category": "Фильтры",
      "item_name": "Фильтр масляный",
      "brand": "VIC C-933",
      "article": "16510-61A31",
      "quantity": 1.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 602.0,
      "total_price": 602.0,
      "interval_km": 7000,
      "interval_hours": 250,
      "next_km": 32340,
      "next_hours": 1022,
      "note": "Плановая замена",
      "store": "Ozon",
      "url": "https://www.ozon.ru/product/maslyanyy-filtr-vic-c-933-c933-dlya-suzuki-grand-vitara-wagon-r-escudo-swift-jimny-sx4-changan-1608071661/?is_apparel_size_selected=true&sh=LpetaRP3Ig"
    },
    {
      "id": 41,
      "vehicle_id": "car_1",
      "to_tag": "ТО-3",
      "date": "2026-07-22",
      "engine_hours": 772,
      "mileage": 25340,
      "category": "Двигатель",
      "item_name": "Масло моторное",
      "brand": "Лукойл Genesis ARMORTECH JP 0W-20",
      "article": "1658134508",
      "quantity": 4.5,
      "unit": "л",
      "price_type": "total",
      "price_per_unit": 807.56,
      "total_price": 3634.0,
      "interval_km": 7000,
      "interval_hours": 250,
      "next_km": 32340,
      "next_hours": 1022,
      "note": "Плановая замена",
      "store": "Ozon",
      "url": "https://www.ozon.ru/product/lukoyl-lukoil-genesis-armortech-jp-0w-20-maslo-motornoe-sinteticheskoe-4-l-1658134508/?oos_search=false&sh=LpetaTdCTw"
    },
    {
      "id": 42,
      "vehicle_id": "car_1",
      "to_tag": "ТО-3",
      "date": "2026-07-22",
      "engine_hours": 772,
      "mileage": 25340,
      "category": "Охлаждение",
      "item_name": "Антифриз (ОЖ)",
      "brand": "FELIX DRAGON G12+",
      "article": "58888973218",
      "quantity": 5.0,
      "unit": "л",
      "price_type": "total",
      "price_per_unit": 325.0,
      "total_price": 1625.0,
      "interval_km": 50000,
      "interval_hours": 250,
      "next_km": 75340,
      "next_hours": 1022,
      "note": "Плановая замена",
      "store": "Ozon",
      "url": "https://www.ozon.ru/product/antifriz-felix-dragon-dlya-kitayskih-avto-40s-g12-5-kg-588897328/?from_sku=588883235&oos_search=false&sh=LpetacWMEQ"
    },
    {
      "id": 43,
      "vehicle_id": "car_1",
      "to_tag": "ТО-3",
      "date": "2026-07-22",
      "engine_hours": 772,
      "mileage": 25340,
      "category": "Зажигание",
      "item_name": "Свечи зажигания CHANGAN",
      "brand": "HU10A80P",
      "article": "3707010-NE01",
      "quantity": 4.0,
      "unit": "шт",
      "price_type": "total",
      "price_per_unit": 1400.0,
      "total_price": 5600.0,
      "interval_km": 30000,
      "interval_hours": 250,
      "next_km": 55340,
      "next_hours": 1022,
      "note": "Плановая замена",
      "store": "Дилер",
      "url": ""
    }
  ],
  "tyre_sets": [
    {
      "id": "tyre_1787939082",
      "vehicle_id": "car_1",
      "name": "Заводской комплект",
      "season": "summer",
      "size": "225/55 R19",
      "brand_model": "",
      "current_km": 10000,
      "tread_depth_mm": 8.0,
      "storage_location": "",
      "is_active": True,
      "install_date": "2026-08-28",
      "install_mileage": 26636
    },
    {
      "id": "tyre_1787939226",
      "vehicle_id": "car_1",
      "name": "Зимние",
      "season": "winter",
      "size": "225/55 R19",
      "brand_model": "Ikon Tures Nordman 8",
      "current_km": 6000,
      "tread_depth_mm": 8.0,
      "storage_location": "Гараж",
      "is_active": False,
      "install_date": "2025-08-31",
      "install_mileage": 20000,
      "quantity": 4.0,
      "price_per_unit": 15705.0,
      "total_price": 62820.0
    }
  ],
  "insurances": [
    {
      "id": "ins_1787940853",
      "vehicle_id": "car_1",
      "type": "kasko",
      "name": "КАСКО",
      "company": "Тинькоф",
      "policy_number": "8786611907",
      "start_date": "2026-08-13",
      "end_date": "2027-08-12",
      "price": 37170.0,
      "note": "",
      "is_active": True,
      "mileage": 26000,
      "engine_hours": 800
    },
    {
      "id": "ins_1787940903",
      "vehicle_id": "car_1",
      "type": "osago",
      "name": "Осаго",
      "company": "Тинькоф",
      "policy_number": "XXX0669194185",
      "start_date": "2026-08-13",
      "end_date": "2027-08-12",
      "price": 5995.0,
      "note": "КБМ 0,46",
      "is_active": True,
      "mileage": 26000,
      "engine_hours": 800
    }
  ]
}

async def test_import():
    await init_db()
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        # Import backup
        res = await ac.post("/api/v1/backup/import", json=USER_BACKUP)
        print("Import response status:", res.status_code)
        assert res.status_code == 200
        data = res.json()
        veh_id = data["vehicle_id"]
        print("Imported Vehicle ID:", veh_id, "Message:", data["message"])

        # Verify vehicle
        v_res = await ac.get(f"/api/v1/vehicles/{veh_id}")
        v = v_res.json()
        print("Vehicle:", v["make"], v["model"], "Plate:", v["license_plate"], "Odometer:", v["current_odometer"], "Hours:", v["current_engine_hours"])
        assert v["make"] == "Changan"
        assert v["current_odometer"] == 26636
        assert v["current_engine_hours"] == 809

        # Verify Service Records
        srv_res = await ac.get(f"/api/v1/service-records?vehicle_id={veh_id}")
        records = srv_res.json()
        print(f"Total Service / Upgrade Records imported: {len(records)}")
        assert len(records) > 0

        # Verify Reminders
        rem_res = await ac.get(f"/api/v1/reminders?vehicle_id={veh_id}")
        reminders = rem_res.json()
        print(f"Total Reminders: {len(reminders)}")
        for r in reminders[:3]:
            print(f" - {r['title']}: interval {r['interval_distance']} km / {r['interval_hours']} h, remaining {r['remaining_distance']} km / {r['remaining_hours']} h, Status: {r['status']}")

        # Verify Tyres
        ty_res = await ac.get(f"/api/v1/tyres?vehicle_id={veh_id}")
        tyres = ty_res.json()
        print(f"Total Tyre Sets: {len(tyres)}")
        assert len(tyres) == 2

        # Verify Documents
        doc_res = await ac.get(f"/api/v1/documents?vehicle_id={veh_id}")
        docs = doc_res.json()
        print(f"Total Documents: {len(docs)}")
        assert len(docs) == 2

        # Verify Analytics
        an_res = await ac.get(f"/api/v1/analytics/{veh_id}")
        an = an_res.json()
        print(f"Total Spend from records: {an['total_spend']} RUB")

    print("\n>>> USER BACKUP IMPORT TEST COMPLETED SUCCESSFULLY! <<<")

if __name__ == "__main__":
    asyncio.run(test_import())
